import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
const workbook=readFileSync(new URL('../demo/workbook.js',import.meta.url),'utf8').split('const database =')[0];
const app=readFileSync(new URL('../demo/app.js',import.meta.url),'utf8').replace(/\nrender\(\);\nloadFiles\(\)[\s\S]*$/,'');
const context=vm.createContext({structuredClone,console,document:{getElementById:()=>({}),addEventListener:()=>{}},window:{},localStorage:{getItem:()=>null,setItem:()=>{}}});
vm.runInContext(workbook+'\n'+readFileSync(new URL('../demo/followups.js',import.meta.url),'utf8')+'\n'+readFileSync(new URL('../demo/review.js',import.meta.url),'utf8')+'\n'+readFileSync(new URL('../demo/operations.js',import.meta.url),'utf8')+'\n'+app,context);
const run=code=>vm.runInContext(code,context);
run(`
function fixtureSheet(name,rows){return {name,headerRow:1,rows:rows.map((values,i)=>({rowNumber:i+1,cells:new Map(values.map((v,j)=>[j,{display:v,value:v,ref:String.fromCharCode(65+j)+(i+1)}]))}))};}
books.sales={fileName:'multi.xlsx',sheetIndex:0,headerRow:1,mapping:{vin:0,dealer:1,email:2},sheets:[fixtureSheet('Sales',[['VIN','经销商','邮箱'],['WBA11CF00RCR79247','测试经销商','dealer@example.invalid']]),fixtureSheet('历史记录',[['VIN','备注'],['WBA22CF00RCR79248','第二张工作表内容']])]};
books.dealers=structuredClone(books.sales);books.dealers.sheets=books.dealers.sheets.slice(0,1);
state.mail={...state.mail,vin:'WBA11CF00RCR79247',dealer:'测试经销商',email:'dealer@example.invalid',subject:'测试',body:'WBA11CF00RCR79247 测试经销商'};
`);
assert.equal(run(`searchRecords('第二张工作表内容').length`),1);
assert.equal(run(`searchRecords('第二张工作表内容')[0].sheet`),1);
assert.equal(run(`searchRecords('第二张工作表内容')[0].row`),2);
assert.equal(run(`checkMail().find(c=>c.field==='收件邮箱').status`),'ok');
assert.equal(run(`checkMail().find(c=>c.field==='金额').status`),'missing');
run(`state.mail.email='wrong@example.invalid';`);
assert.equal(run(`checkMail().find(c=>c.field==='收件邮箱').status`),'diff');
run(`books.sales.sheets[0].rows.push({...books.sales.sheets[0].rows[1],rowNumber:3});`);
assert.match(run(`checkMail()[0].text`),/多条同 VIN/);
assert.equal(run(`safeArchivePath('../escape.txt')`),false);
assert.equal(run(`safeArchivePath('dealer/../../escape.txt')`),false);
assert.equal(run(`safeArchivePath('C:\\test.txt')`),false);
assert.equal(run(`safeArchivePath('dealer/材料.pdf')`),true);
assert.deepEqual(JSON.parse(run(`JSON.stringify(parseCsv('名称,备注\\r\\n经销商,"包含,逗号"\\r\\n'))`)),[['名称','备注'],['经销商','包含,逗号']]);
console.log('PASS: multi-sheet search, source rows, missing fields, mismatches, duplicate VIN, archive paths, CSV quoting.');

run(`books.sales.sheets[0].rows.pop();books.sales.sheets[0].rows[1].cells.get(2).display='old-contact@example.invalid';state.mail.email='dealer@example.invalid';`);
assert.equal(run(`checkMail().find(c=>c.field==='收件邮箱').status`),'ok','Directory is authoritative for contact information');
run(`state.mailChecked=true;invalidateMail();`);
assert.equal(run(`state.mailStale`),true);
run(`const changed=structuredClone(books.sales);changed.sheets[0].rows[1].cells.get(1).display='新经销商';const comparison=compareBooks(books.sales,changed);`);
assert.equal(run(`comparison.items.length`),1);
assert.equal(run(`comparison.items[0].decision`),'defer');
assert.equal(run(`comparison.items[0].ref`),'B2');
run(`changed.sheets[0].rows[1].cells.get(1).formula='A1';`);
assert.equal(run(`compareBooks(books.sales,changed).items.length`),0);
assert.match(run(`JSON.stringify(compareBooks(books.sales,changed).issues)`),/公式/);
run(`changed.sheets[0].rows.push({...changed.sheets[0].rows[1],rowNumber:3});`);
assert.match(run(`JSON.stringify(compareBooks(books.sales,changed).issues)`),/重复 VIN/);
console.log('PASS: contact authority, stale mail checks, deferred comparisons, source refs, formula and duplicate guards.');
run(`const formulaBase=structuredClone(books.sales),formulaNext=structuredClone(books.sales);formulaBase.sheets[0].rows[1].cells.get(2).formula='A1';`);
assert.ok(run(`compareBooks(formulaBase,formulaNext).issues.some(i=>i.category==='formula')`),'Missing formula must be detected even when displayed value is identical');
run(`const typed=structuredClone(books.sales);typed.mapping.amount=2;typed.sheets[0].rows[1].cells.get(2).display='未知金额';`);
assert.ok(run(`validateFields(typed).some(i=>i.category==='format')`));
assert.equal(run(`unresolved({items:[],issues:[{decision:'defer'}]})`),1);
assert.equal(run(`taskStatus({items:[],issues:[]})`),'处理中');
assert.equal(run(`taskStatus({items:[],issues:[],completedAt:'2026-09-08'})`),'已完成');
console.log('PASS: formula integrity, typed format suggestions, unresolved issues and explicit completion.');
