'use strict';
let followupDraft=null,followupFilter='all';
const followupFiles={};
function followupList(){return state.followups||[];}
function dueToday(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function overdue(t){return t.status!=='已完成'&&t.due&&t.due<dueToday();}
function taskEvent(t,action,detail=''){t.events??=[];t.events.push({time:new Date().toLocaleString('zh-CN'),action,detail});saveState();}
function followupSummary(){const all=followupList();return `<section class="card followup-home"><div class="card-head"><h2>问题跟进</h2><div class="button-row">${[['all','全部'],['等待资料','待补材料'],['待复核','待确认'],['overdue','已逾期']].map(([key,label])=>`<button class="button ${followupFilter===key?'secondary':'ghost'} small" data-followup-filter="${key}">${label} ${all.filter(t=>key==='all'||key==='overdue'?key==='all'||overdue(t):t.status===key).length}</button>`).join('')}</div></div><div class="card-body">${followupRows(all.filter(t=>followupFilter==='all'||(followupFilter==='overdue'?overdue(t):t.status===followupFilter)).sort((a,b)=>Number(overdue(b))-Number(overdue(a))||(a.due||'9999').localeCompare(b.due||'9999')))}</div></section>`;}
function followupRows(rows){return rows.map(t=>`<div class="work-row"><div><strong>${esc(t.title)}</strong><p>${esc(vinLabel(t.vin))} · ${esc(t.owner||'待分配')} · ${esc(t.due||'未设日期')}</p></div><div class="button-row"><span class="status ${overdue(t)?'red':t.status==='已完成'?'green':'amber'}">${overdue(t)?'已逾期 · ':''}${esc(t.status)}</span><button class="button secondary small" data-open-followup="${t.id}">处理</button></div></div>`).join('')||'<p class="subtle empty-copy">暂无跟进事项</p>';}
function taskSource(key,kind,index){const c=comparisons[key];if(!c)return null;const item=(kind==='change'?c.items:c.issues)[index];if(!item)return null;const matches=bookRows(c.source).filter(r=>mapped(r,c.source,'vin').toUpperCase()===item.vin.toUpperCase());return {key,kind,index,reviewId:c.id||c.createdAt,vin:item.vin,dealer:matches.length===1?mapped(matches[0],c.source,'dealer'):'',title:kind==='change'?`${item.field}差异待核对`:item.reason,sourceName:c.sourceName,sourceSheet:c.sourceSheet,sourceRef:item.sourceRef||item.ref||'',original:kind==='change'?`${item.oldValue} → ${item.newValue}`:item.reason};}
function openFollowupForm(source){if(!source)return;const existing=followupList().find(t=>t.source.reviewId===source.reviewId&&t.source.kind===source.kind&&t.source.index===source.index);if(existing){showFollowup(existing.id);return;}followupDraft=source;detail('创建跟进任务',`<form class="panel-pad" id="followupForm"><label class="form-field">待处理问题<input name="title" required maxlength="300" value="${esc(source.title)}"></label><div class="form-pair"><label class="form-field">完整 VIN<input name="vin" required pattern="[A-HJ-NPR-Za-hj-npr-z0-9]{17}" value="${esc(source.vin)}"></label><label class="form-field">经销商<input name="dealer" required maxlength="150" value="${esc(source.dealer)}"></label></div><div class="form-pair"><label class="form-field">负责人<input name="owner" required maxlength="100"></label><label class="form-field">跟进日期<input name="due" required type="date" value="${dueToday()}"></label></div><label class="review-confirm"><input type="checkbox" required> 已确认该问题需要跟进</label><button class="button primary">创建任务</button></form>`);}
function showFollowup(id){const t=followupList().find(t=>t.id===id);if(!t)return;const files=followupFiles[id]||[];detail('问题跟进',`<div class="panel-pad"><div class="comparison-intro"><div><h3>${esc(t.title)}</h3><p class="subtle">${esc(vinLabel(t.vin))} · ${esc(t.dealer)}</p></div><span class="status ${t.status==='已完成'?'green':'amber'}">${esc(t.status)}</span></div><form id="followupOwnerForm" data-id="${id}"><div class="form-pair"><label class="form-field">负责人<input name="owner" required maxlength="100" value="${esc(t.owner)}"></label><label class="form-field">跟进日期<input name="due" required type="date" value="${esc(t.due)}"></label></div><button class="button ghost small">保存安排</button></form><div class="toolbar followup-actions"><button class="button primary" data-followup-mail="${id}">生成通知</button><button class="button secondary" data-followup-receive="${id}" ${t.status==='已完成'?'disabled':''}>添加反馈材料</button><button class="button secondary" data-followup-recheck="${id}" ${!files.length||t.status==='已完成'?'disabled':''}>复核材料</button></div><details class="source-fold"><summary>核查依据</summary><p>${esc(t.source.sourceName)} · ${esc(t.source.sourceSheet)} · ${esc(t.source.sourceRef)}</p><p>${esc(t.source.original)}</p></details><div class="materials-list">${files.map((f,i)=>`<div class="record-row"><span>${esc(f.name)}</span><button class="button ghost small" data-followup-file="${id}" data-file-index="${i}">打开材料</button></div>`).join('')}</div><h3 class="timeline-title">处理记录</h3><div class="followup-timeline">${(t.events||[]).slice().reverse().map(e=>`<div><time>${esc(e.time)}</time><strong>${esc(e.action)}</strong><p>${esc(e.detail)}</p></div>`).join('')}</div></div>`);}
function makeFollowupMail(id){const t=followupList().find(t=>t.id===id);if(!t)return;const b=books.dealers,contacts=b?bookRows(b).filter(r=>mapped(r,b,'dealer')===t.dealer):[];state.mail={templateId:'followup',followupId:id,vin:t.vin,dealer:t.dealer,email:contacts.length===1?mapped(contacts[0],b,'email'):'',phone:contacts.length===1?mapped(contacts[0],b,'phone'):'',address:contacts.length===1?mapped(contacts[0],b,'address'):'',amount:'',date:'',subject:`资料核对通知 · ${t.dealer}`,body:`${t.dealer}，你好：\n\n请协助核对以下车辆资料。\nVIN：${t.vin}\n待处理问题：${t.title}\n请于 ${t.due} 前反馈相关资料。\n\n谢谢。`};if(!state.templates.some(t=>t.id==='followup'))state.templates.push({id:'followup',name:'问题跟进',subject:'资料核对通知 · {{经销商}}',body:'{{经销商}}，你好：\nVIN：{{VIN}}\n请协助核对车辆资料。'});invalidateMail();taskEvent(t,'通知草稿已生成');closeDetail();navigate('mail');}
function linkedMailBanner(){const t=followupList().find(t=>t.id===state.mail.followupId);return t?`<div class="linked-notice"><div><strong>${esc(t.title)}</strong><span>${esc(t.owner)} · ${esc(t.due)}</span></div><button class="button ghost small" data-open-followup="${t.id}">查看跟进</button></div>`:'';}
function followupMailEvent(action){const t=followupList().find(t=>t.id===state.mail.followupId);if(t)taskEvent(t,action,'收件人：'+state.mail.email);}
document.addEventListener('click',async event=>{const el=event.target.closest('button');if(!el)return;try{
if(el.dataset.followupFilter){followupFilter=el.dataset.followupFilter;render();}
if(el.dataset.openFollowup){showFollowup(el.dataset.openFollowup);}
if(el.dataset.createFollowup!==undefined){openFollowupForm(taskSource(comparisonKey,el.dataset.findingKind,Number(el.dataset.createFollowup)));}
if(el.dataset.inventoryFollowup){const row=bookRows(books.inventory).find(r=>r.rowNumber===Number(el.dataset.inventoryFollowup));openFollowupForm({key:'inventory',kind:'inventory',index:row.rowNumber,reviewId:`inventory-${books.inventory.version||1}-${state.materialRevision||0}`,vin:mapped(row,books.inventory,'vin'),dealer:mapped(row,books.inventory,'dealer'),title:'车辆材料待补充',sourceName:books.inventory.fileName,sourceSheet:books.inventory.sheets[books.inventory.sheetIndex||0].name,sourceRef:'第 '+row.rowNumber+' 行',original:'盘点清单中的车辆未找到匹配材料，请确认缺失项。'});}
if(el.dataset.followupMail){makeFollowupMail(el.dataset.followupMail);}
if(el.dataset.followupReceive){document.getElementById('followupFileInput').dataset.taskId=el.dataset.followupReceive;document.getElementById('followupFileInput').click();}
if(el.dataset.followupFile){const f=followupFiles[el.dataset.followupFile]?.[Number(el.dataset.fileIndex)];if(f)download(f.blob,f.name);}
if(el.dataset.followupRecheck){const t=followupList().find(t=>t.id===el.dataset.followupRecheck);detail('复核反馈材料',`<form class="panel-pad" id="followupRecheckForm" data-id="${t.id}"><h3>${esc(t.title)}</h3><p class="subtle">${esc(vinLabel(t.vin))}</p><label class="form-field">复核结果<select name="result"><option value="pass">问题已解决</option><option value="return">仍需补充资料</option></select></label><label class="form-field">复核依据<textarea name="note" required rows="3" maxlength="1000"></textarea></label><label class="review-confirm"><input type="checkbox" required> 已打开材料，核对车辆与问题内容</label><button class="button primary">确认复核</button></form>`);}
}catch(e){toast(e.message||'操作未完成');}});
document.addEventListener('submit',event=>{const form=event.target;if(!['followupForm','followupOwnerForm','followupRecheckForm'].includes(form.id))return;event.preventDefault();const data=new FormData(form);
if(form.id==='followupForm'){if(!followupDraft)return;const t={id:crypto.randomUUID(),source:structuredClone(followupDraft),title:String(data.get('title')).trim(),vin:String(data.get('vin')).trim().toUpperCase(),dealer:String(data.get('dealer')).trim(),owner:String(data.get('owner')).trim(),due:data.get('due'),status:'等待资料',events:[]};if(!t.title||!t.dealer||!t.owner)return toast('请填写问题、经销商与负责人。');state.followups??=[];state.followups.push(t);followupDraft=null;taskEvent(t,'跟进任务已创建',t.source.sourceName+' · '+t.source.sourceRef);log('创建跟进任务',t.title);render();showFollowup(t.id);return;}
const t=followupList().find(t=>t.id===form.dataset.id);if(!t)return;
if(form.id==='followupOwnerForm'){const owner=String(data.get('owner')).trim();if(!owner)return toast('请填写负责人');t.owner=owner;t.due=data.get('due');taskEvent(t,'跟进安排已更新',`${t.owner} · ${t.due}`);showFollowup(t.id);return;}
if(t.status==='已完成'||!followupFiles[t.id]?.length)return toast('请先添加反馈材料');const note=String(data.get('note')).trim();if(!note)return toast('请填写复核依据');t.status=data.get('result')==='pass'?'已完成':'等待资料';taskEvent(t,t.status==='已完成'?'复核通过，问题已解决':'复核退回',note);log('反馈材料复核',`${t.vin} · ${t.status} · ${note}`);render();showFollowup(t.id);
});
document.addEventListener('change',async event=>{const el=event.target;if(el.id!=='followupFileInput'||!el.files.length)return;const id=el.dataset.taskId,t=followupList().find(t=>t.id===id);if(!t)return;try{const entries=[...el.files].map(f=>({name:f.name,blob:f}));if(entries.some(f=>f.blob.size>50*1024*1024))throw new Error('单份材料不能超过 50 MB');const all=[...(followupFiles[id]||[]),...entries];if(all.reduce((n,f)=>n+f.blob.size,0)>150*1024*1024)throw new Error('任务材料总量不能超过 150 MB');await storeFile('followup-files:'+id,all);followupFiles[id]=all;t.status='待复核';taskEvent(t,'反馈材料已收到',entries.map(f=>f.name).join('、'));render();showFollowup(id);}catch(e){toast(e.message);}finally{el.value='';}});
