'use strict';
const comparisons={};
const reviewHistory=[];
let reviewFilter='all',taskFilter='all';
let comparisonKey='';
function pendingCount(){return Object.values(comparisons).reduce((n,c)=>n+unresolved(c),0);}
function invalidateMail(){if(state.mailChecked)state.mailStale=true;mailCheck=null;const result=document.getElementById('mailCheckResult');if(result)result.innerHTML='';updateMailStatus();}
function updateMailStatus(){const el=document.getElementById('mailStatus');if(!el)return;const status=state.mailStale?'需重新核查':!mailCheck?'待核查':mailCheck.some(c=>c.status==='diff')?'发现差异':mailCheck.some(c=>c.status==='missing')?'依据不完整':'核查通过';el.textContent=status;el.className='status '+(status==='核查通过'?'green':status==='发现差异'?'red':'amber');}
function versionPanel(key){const b=books[key],c=comparisons[key];if(!b)return '';return `<section class="version-panel"><div><strong>当前依据 · v${b.version||1}</strong><p>${esc(b.fileName)} · ${esc(b.sheets[b.sheetIndex||0].name)}</p><small>${b.importedAt?'导入于 '+esc(new Date(b.importedAt).toLocaleString('zh-CN')):'历史导入 · 时间未记录'}${b.modifiedAt?' · 修改于 '+esc(new Date(b.modifiedAt).toLocaleString('zh-CN')):''}</small></div><div class="button-row"><button class="button primary" data-action="compare-import" data-key="${key}">运行核查</button>${c?`<button class="button secondary" data-action="review-comparison" data-key="${key}">审查差异 · ${unresolved(c)}</button>`:''}</div></section>`;}
function compareBooks(base,source){
  if(base.mapping?.vin<0||source.mapping?.vin<0||base.mapping?.vin===undefined||source.mapping?.vin===undefined)throw new Error('两份表都需要映射完整 VIN 列。');
  const items=[],issues=[],a=new Map(),b=new Map();
  function index(book,map,label){for(const row of bookRows(book)){const vin=mapped(row,book,'vin').toUpperCase();if(!/^[A-HJ-NPR-Z0-9]{17}$/.test(vin)){issues.push({vin:vin||'空 VIN',reason:`${label}第 ${row.rowNumber} 行：VIN 不完整，未匹配`});continue;}if(!map.has(vin))map.set(vin,[]);map.get(vin).push(row);}}
  index(base,a,'原表');index(source,b,'更新表');
  const ah=bookHeaders(base),bh=bookHeaders(source),fields=[];
  // Only unambiguous same-name columns, or explicitly mapped fields, can be compared.
  for(const h of ah){if(h.index===base.mapping.vin)continue;const mappedField=Object.keys(base.mapping).find(k=>k!=='vin'&&base.mapping[k]===h.index&&source.mapping[k]>=0);const matches=mappedField?bh.filter(x=>x.index===source.mapping[mappedField]):bh.filter(x=>x.label.trim()===h.label.trim());
    if(matches.length===1&&ah.filter(x=>x.label.trim()===h.label.trim()).length===1)fields.push([h,matches[0]]);else issues.push({vin:'字段',reason:`${h.label}：更新表缺列或表头重复，未比较`});}
  for(const [vin,rows] of b){const originals=a.get(vin)||[];if(rows.length!==1||originals.length>1){issues.push({vin,reason:'重复 VIN，需先确认唯一记录'});continue;}
    if(!originals.length){issues.push({vin,reason:`新增车辆 · 更新表第 ${rows[0].rowNumber} 行，请在 Excel 中确认新增`});continue;}
    const old=originals[0],next=rows[0];for(const [h,sh]of fields){const oc=old.cells.get(h.index),nc=next.cells.get(sh.index);if(!nc){issues.push({vin,reason:`${sh.label}：更新表缺少单元格，未比较`});continue;}if(oc?.formula&&!nc.formula){issues.push({vin,category:'formula',reason:`${h.label}：原表有公式，更新表未保留`,row:next.rowNumber,ref:nc.ref,suggestion:'核对公式是否应保留',certainty:'待确认'});continue;}if((oc?.display||'')===nc.display)continue;
      const blocked=!oc||oc.formula||oc.merged||nc.formula||nc.merged;
      if(blocked){issues.push({vin,reason:`${h.label}：涉及公式、合并区或原表空缺单元格，请在 Excel 中处理`});continue;}
      items.push({vin,field:h.label,ref:oc.ref,row:old.rowNumber,sourceRow:next.rowNumber,sourceRef:nc.ref,oldValue:oc.display,newValue:nc.display,decision:'defer'});
    }
  }
  for(const [vin,rows]of a)if(!b.has(vin))issues.push({vin,reason:rows.length>1?'原表重复 VIN，未比较':'更新表未包含该车辆；保留原记录'});
  issues.push(...validateFields(source));
  issues.forEach(i=>{i.category??=classifyIssue(i);i.decision??='defer';i.certainty??='待确认';});
  return {items,issues};
}
async function createComparison(key,source){const base=books[key];if(!base)throw new Error('请先导入原表。');if(comparisons[key]&&!comparisons[key].completedAt)throw new Error('请先处理现有差异，再导入下一份更新表。');const result=compareBooks(base,source),c={...result,baseVersion:base.version||1,baseName:base.fileName,sourceName:source.fileName,sourceSheet:source.sheets[source.sheetIndex||0].name,sheetIndex:base.sheetIndex||0,createdAt:new Date().toISOString(),source,id:crypto.randomUUID(),status:'review'};await storeFile('comparison:'+key,c);comparisons[key]=c;log('表格差异已生成',`${base.fileName} ← ${source.fileName} · ${c.items.length} 处差异 · ${c.issues.length} 个核查项`);closeDetail();render();showComparison(key);}
async function applyComparison(){const key=comparisonKey,c=comparisons[key],base=books[key];if((base.version||1)!==c.baseVersion)throw new Error('原表版本已变更，请重新对比。');const accepted=c.items.filter(i=>i.decision==='accept');if(!accepted.length)throw new Error('请先选择需要接受的修改。');const view={...base,sheetIndex:c.sheetIndex},changes=Object.fromEntries(accepted.map(i=>[i.ref,i.newValue]));const blob=await changedWorkbook(view,changes),name=base.fileName.replace(/\.(xlsx|csv)$/i,'-已核查.$1'),updated=await readWorkbook(new File([blob],name));Object.assign(updated,{sheetIndex:base.sheetIndex,headerRow:base.headerRow,mapping:base.mapping,version:(base.version||1)+1,importedAt:base.importedAt,modifiedAt:new Date().toISOString()});const next=structuredClone(c);next.items.filter(i=>i.decision==='accept').forEach(i=>i.decision='applied');next.exportedAt=new Date().toISOString();next.baseVersion=updated.version;next.baseName=name;
  // Save the workbook and its review decisions in the same transaction.
  const db=await database;await new Promise((resolve,reject)=>{const tx=db.transaction('files','readwrite'),store=tx.objectStore('files');store.put(updated,'book:'+key);store.put(next,'comparison:'+key);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('保存被中断'));});books[key]=updated;comparisons[key]=next;invalidateMail();log('差异修改已确认',`${name} · ${accepted.map(i=>`${i.ref}: ${i.oldValue} → ${i.newValue}`).join('；')}`);download(blob,name);render();showComparison(key);}
function openAssistant(){const d=document.getElementById('askDialog');document.getElementById('askContext').textContent=`当前范围：${document.getElementById('currentPageLabel').textContent}${route==='sheets'&&books[selectedJob]?' · '+books[selectedJob].fileName:''}`;if(window.JOYoneAgent){window.JOYoneAgent.open('demo');return;}if(!d.open)d.show();document.getElementById('askInput').focus();}
function submitAsk(){const prompt=document.getElementById('askInput').value.trim();if(!prompt)return;const node=document.getElementById('askAnswer');node.hidden=false;let body;
  if(prompt==='查看待办')body=`<p>表格待审查 ${pendingCount()} 项；车辆待跟进 ${state.transfers.filter(t=>!t.sample&&t.steps.some(v=>!v)).length} 辆。</p><button class="button secondary small" data-assistant-route="today">打开今日工作</button>`;
  else if(prompt==='查看库存候选'){const g=inventoryGroups();body=`<p>${g?`完整 VIN 文件名候选 ${g.matched.length} 辆；待人工匹配 ${g.review.length} 辆；未找到材料 ${g.missing.length} 辆。`:'尚未导入盘点表。'}</p><button class="button secondary small" data-assistant-route="sheets" data-key="inventory">查看库存</button>`;}
  else if(prompt==='查看表格差异')body=`<p>${pendingCount()} 项待审查。</p><button class="button secondary small" data-assistant-route="sheets">打开表格</button>`;
  else if(prompt==='打开邮件草稿')body='<p>使用已导入资料填写模板并核查字段。</p><button class="button secondary small" data-assistant-route="mail">打开邮件</button>';
  else {const results=searchRecords(prompt);body=`<p>找到 ${results.length} 条记录。</p>${results.slice(0,4).map(r=>`<p>${esc(r.title)}</p>`).join('')}<button class="button secondary small" data-assistant-search="${esc(prompt)}">查看搜索结果</button>`;}
  node.innerHTML='<strong>查询结果</strong>'+body;
}
document.addEventListener('click',async event=>{const el=event.target.closest('button');if(!el)return;try{
  const action=el.dataset.action,key=el.dataset.key;
  if(el.dataset.inventoryReview!==undefined){const row=Number(el.dataset.inventoryReview),list=materials.inventory||[];detail('核对车辆材料',`<form class="panel-pad" id="inventoryReviewForm" data-row="${row}"><p>盘点表第 ${row} 行 · 选择已打开核对的材料</p>${list.map((f,i)=>`<div class="evidence-row"><label><input type="checkbox" name="files" value="${i}"> ${esc(f.name)}</label><button type="button" class="button ghost small" data-evidence-open="${i}">打开</button></div>`).join('')||empty('尚未导入材料。')}<label class="review-confirm"><input type="checkbox" name="verified" required> 我已核对车辆身份与材料内容，并确认所选材料齐全</label><button class="button primary" ${list.length?'':'disabled'}>确认材料</button></form>`);}
  if(el.dataset.evidenceOpen!==undefined){const f=materials.inventory[Number(el.dataset.evidenceOpen)];download(f.blob,f.name.split('/').at(-1));toast('材料已下载，请打开核对后确认。');}
  if(action==='toggle-sidebar'){document.body.classList.toggle('sidebar-collapsed');el.setAttribute('aria-expanded',String(!document.body.classList.contains('sidebar-collapsed')));}
  if(action==='compare-import'){importKey='compare:'+key;document.getElementById('workbookInput').click();}
  if(action==='review-comparison'){showComparison(key);}
  if(action==='apply-comparison'){el.disabled=true;await applyComparison();}
  if(action==='recompare'){const c=comparisons[comparisonKey],key=comparisonKey;const fresh={...c,completedAt:null,status:'review',...compareBooks(books[key],c.source),baseVersion:books[key].version||1,baseName:books[key].fileName};await storeFile('comparison:'+key,fresh);comparisons[key]=fresh;log('重新核查',fresh.sourceName);showComparison(key);}
  if(action==='export-review'){const c=comparisons[comparisonKey],rows=[['来源文件',c.sourceName,'依据文件',c.baseName],['VIN','问题类别','原值','建议值 / 发现','原表位置','更新表位置','人工决定','处理依据'],...c.items.map(i=>[i.vin,'字段变化',i.oldValue,i.newValue,i.ref,i.sourceRef,decisionLabels[i.decision],'']),...c.issues.map(i=>[i.vin,reviewCategories[i.category||classifyIssue(i)],'',i.reason,'',i.ref||'',decisionLabels[i.decision]||'暂缓',i.note||''])];const csv=rows.map(r=>r.map(v=>'"'+String(v??'').replace(/^[=+@-]/,m=>"'"+m).replace(/"/g,'""')+'"').join(',')).join('\r\n');download(new Blob(['\uFEFF',csv],{type:'text/csv;charset=utf-8'}),'JOYone-核查报告.csv');}

  if(el.dataset.diffSource!==undefined){const c=comparisons[comparisonKey],i=c.items[Number(el.dataset.diffSource)],row=bookRows(c.source).find(r=>r.rowNumber===i.sourceRow);detail('差异依据',`<div class="panel-pad"><p>${esc(c.sourceName)} · ${esc(c.sourceSheet)} · 第 ${i.sourceRow} 行</p>${readOnlyTable(bookHeaders(c.source),[row])}<p class="subtle">原表 ${esc(c.baseName)} · ${esc(i.ref)}：${esc(i.oldValue)}</p><button class="button secondary" data-action="review-comparison" data-key="${comparisonKey}">返回差异审查</button></div>`);}
  if(action==='mail-source'){const b=books[key];if(!b)throw new Error('请先导入依据表格。');const row=bookRows(b).find(r=>key==='sales'?mapped(r,b,'vin').toUpperCase()===state.mail.vin.trim().toUpperCase():mapped(r,b,'dealer')===state.mail.dealer);if(!row)throw new Error('没有找到对应记录。');openBook(key,row.rowNumber);}
  if(el.dataset.assistantRoute){if(el.dataset.key)selectedJob=el.dataset.key;document.getElementById('askDialog').close();navigate(el.dataset.assistantRoute);}
  if(el.dataset.assistantSearch!==undefined){searchQuery=el.dataset.assistantSearch;searchPage=0;document.getElementById('askDialog').close();navigate('search');}
  if(el.dataset.vehicleSearch!==undefined){searchQuery=state.transfers[Number(el.dataset.vehicleSearch)].vin;searchPage=0;navigate('search');}
  if(el.dataset.transferNote!==undefined){const index=Number(el.dataset.transferNote),t=state.transfers[index];detail('备注与材料',`<form class="panel-pad" id="transferNoteForm" data-index="${index}"><p>${esc(vinLabel(t.vin))} · ${esc(t.dealer)}</p><label class="form-field">办理备注<textarea name="note" rows="3" maxlength="2000">${esc(t.note||'')}</textarea></label><label class="form-field">关联材料名称或归档位置<input name="evidence" maxlength="1000" value="${esc(t.evidence||'')}"></label><button class="button primary">保存</button></form>`);}
}catch(e){el.disabled=false;toast(e.message||'操作未完成。');}});
document.addEventListener('change',async event=>{const el=event.target;if(el.dataset.diffDecision===undefined)return;try{const key=comparisonKey,next=structuredClone(comparisons[key]);next.items[Number(el.dataset.diffDecision)].decision=el.value;await storeFile('comparison:'+key,next);comparisons[key]=next;log('人工决定',`${next.sourceName} · ${next.items[Number(el.dataset.diffDecision)].ref} · ${{defer:'暂缓',accept:'接受',keep:'保留原值'}[el.value]}`);showComparison(key);}catch(e){toast('审查决定保存失败，请重试。');showComparison(comparisonKey);}});
document.addEventListener('submit',event=>{const form=event.target;if(form.id==='inventoryReviewForm'){event.preventDefault();const data=new FormData(form),files=data.getAll('files').map(i=>materials.inventory[Number(i)]?.name).filter(Boolean);if(!files.length)return toast('请选择已核对的材料。');state.inventoryReviews??={};state.inventoryReviews[form.dataset.row]={files,version:books.inventory.version||1,materialRevision:state.materialRevision||0,time:new Date().toLocaleString('zh-CN')};log('车辆材料人工确认',`盘点表第 ${form.dataset.row} 行 · ${files.join('、')}`);closeDetail();render();return;}if(form.id!=='transferNoteForm')return;event.preventDefault();const t=state.transfers[Number(form.dataset.index)],data=new FormData(form);t.note=String(data.get('note')).trim();t.evidence=String(data.get('evidence')).trim();log('过户备注已更新',`${t.vin} · ${t.note} · ${t.evidence}`);closeDetail();render();});
